#!/usr/bin/env bash
set -e -o pipefail

# Add repo specific metadata here.

BASE_IMAGE_PATTERN='bookworm-([0-9]+)-slim'
BASE_IMAGE_CONFIG_KEY_PREFIX="UPSTREAM_IMAGE"

RELEASE_PACKAGE_NAME="Debian"
RELEASE_TAG_SKIP_PACKAGE_NAME="y"
RELEASE_UPDATE_BASE_IMAGE="n"

UPSTREAM_PACKAGE_NAME="Debian"
UPSTREAM_VERSION_CONFIG_KEY="UPSTREAM_IMAGE_TAG"

TEST_TYPE="foreground"
TEST_CONTAINER_TYPE="base"

current_upstream_version() {
    get_config_arg ${UPSTREAM_VERSION_CONFIG_KEY:?}
}

latest_upstream_version() {
    latest_base_image_tag
}

update_latest_upstream_version() {
    local cur_ver="${1:?}"
    local latest_ver="${2:?}"
    echo "Updating ${PACKAGE_NAME:?} ${UPSTREAM_VERSION_CONFIG_KEY:?} '${cur_ver:?}' -> '${latest_ver:?}'"
    set_config_arg "${UPSTREAM_VERSION_CONFIG_KEY:?}" "${latest_ver:?}"
    git add ${ARGS_FILE:?}
}

package_current_release_version() {
    current_upstream_version
}

test_start_container() {
    local container_name="${1:?}"
    docker run \
        --name ${container_name:?} \
        --rm \
        ${IMAGE:?} \
        sh -c \
        'apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install nginx'
}
