#!/usr/bin/env bash
set -E -e -o pipefail

FORMAT_PREFIX="\x1b["
FORMAT_SUFFIX="m"
FORMAT_OPTION_SEPARATOR=";"
FORMAT_OPTION_RESET="0"
FORMAT_OPTION_BOLD="1"

FORMAT_COLOR_BLACK="30"
FORMAT_COLOR_RED="31"
FORMAT_COLOR_GREEN="32"
FORMAT_COLOR_YELLOW="33"
FORMAT_COLOR_BLUE="34"
FORMAT_COLOR_MAGENTA="35"
FORMAT_COLOR_CYAN="36"
FORMAT_COLOR_WHITE="37"
FORMAT_COLOR_NONE="0"

FORMAT_FATAL="${FORMAT_PREFIX:?}${FORMAT_OPTION_BOLD:?}${FORMAT_OPTION_SEPARATOR:?}${FORMAT_COLOR_RED:?}${FORMAT_SUFFIX:?}"
FORMAT_ERROR="${FORMAT_PREFIX:?}${FORMAT_COLOR_RED:?}${FORMAT_SUFFIX:?}"
FORMAT_WARN="${FORMAT_PREFIX:?}${FORMAT_COLOR_YELLOW:?}${FORMAT_SUFFIX:?}"
FORMAT_INFO="${FORMAT_PREFIX:?}${FORMAT_COLOR_BLUE:?}${FORMAT_SUFFIX:?}"
FORMAT_DEBUG="${FORMAT_PREFIX:?}${FORMAT_COLOR_GREEN:?}${FORMAT_SUFFIX:?}"
FORMAT_TRACE="${FORMAT_PREFIX:?}${FORMAT_COLOR_MAGENTA:?}${FORMAT_SUFFIX:?}"
FORMAT_ANY_RESET="${FORMAT_PREFIX:?}${FORMAT_OPTION_RESET:?}${FORMAT_SUFFIX:?}"

TIMESTAMP_FORMAT="+%Y-%m-%dT%T.%3N%z"

# 0 - Fatal, Err
# 1 - Fatal, Err, Warn
# 2 - Fatal, Err, Warn, Info
# 3 - Fatal, Err, Warn, Info, Debug
# 4 - Fatal, Err, Warn, Info, Debug, Trace
LOGGER_LEVEL=2

logFatal() {
    echo -e "$(date "${TIMESTAMP_FORMAT:?}")  ${FORMAT_FATAL:?}FATAL${FORMAT_ANY_RESET:?} " "$@"
    exit 1
}

logErr() {
    echo -e "$(date "${TIMESTAMP_FORMAT:?}")  ${FORMAT_ERROR:?}ERROR${FORMAT_ANY_RESET:?} " "$@"
}

logWarn() {
    if [ "${LOGGER_LEVEL:?}" -gt 0 ]; then
        echo -e "$(date "${TIMESTAMP_FORMAT:?}")  ${FORMAT_WARN:?}WARN${FORMAT_ANY_RESET:?}  " "$@"
    fi
}

logInfo() {
    if [ "${LOGGER_LEVEL:?}" -gt 1 ]; then
        echo -e "$(date "${TIMESTAMP_FORMAT:?}")  ${FORMAT_INFO:?}INFO${FORMAT_ANY_RESET:?}  " "$@"
    fi
}

logDebug() {
    if [ "${LOGGER_LEVEL:?}" -gt 2 ]; then
        echo -e "$(date "${TIMESTAMP_FORMAT:?}")  ${FORMAT_DEBUG:?}DEBUG${FORMAT_ANY_RESET:?} " "$@"
    fi
}

logTrace() {
    if [ "${LOGGER_LEVEL:?}" -gt 3 ]; then
        echo -e "$(date "${TIMESTAMP_FORMAT:?}")  ${FORMAT_TRACE:?}TRACE${FORMAT_ANY_RESET:?} " "$@"
    fi
}

logEmpty() {
    if [ "${LOGGER_LEVEL:?}" -gt 0 ]; then
        echo
    fi
}

logEmptyInfo() {
    if [ "${LOGGER_LEVEL:?}" -gt 1 ]; then
        echo
    fi
}

logEmptyDebug() {
    if [ "${LOGGER_LEVEL:?}" -gt 2 ]; then
        echo
    fi
}

logEmptyTrace() {
    if [ "${LOGGER_LEVEL:?}" -gt 3 ]; then
        echo
    fi
}
