#!/usr/bin/env bash
set -E -e -o pipefail

nowEpoch() {
    date +%s.%N
}

offsetEpoch() {
    date -d "${1:?}" +%s.%N
}

sleepUntil() {
    local now=$(nowEpoch)
    local target=${1:?}
    local duration=$(echo "${target:?} - ${now:?}" | bc)
    sleep ${duration:?}
}
